version: '3'
services:
  # Django web application
  web:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  # Postgres database
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password