version: '3'
services:
  # Postgres database
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  # Django web application
  web:
    depends_on:
      - db
      - redis
    container_name: django_app
    environment:
      - DATABASE_HOST=db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379