# Generated by Django 4.2.4 on 2023-09-03 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formulaire", "0003_visiteur"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EndpointVisitor",
        ),
        migrations.DeleteModel(
            name="Visiteur",
        ),
    ]
