#name of the workflow
name: CI/CD PIPELINE django

# Déclenchez le workflow chaque fois qu'une modification est poussée vers la branche principale ou qu'une demande d'extraction est ouverte.
on: 

  push:
    branches:  main

  pull_request:
    branches: main
#action à executer
jobs:
  build-ci:
    runs-on:  ubuntu-latest 
    container: python:3.11.4-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: pip install -r requirements.txt
        working-directory: ./devopsprojetclasse

      - name: Check the formatting
        run: black . --check

      - name: Check the linting
        run: ruff check .

      - name: Run pytest inside 
        run: pytest test.py
        working-directory: ./formulaire
    
      -name: Login on registre Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      -name: image docker build
        run: docker build -t Django_image
        working-directory: ./devopsprojetclasse

      -name: push to registre docker
        run: |
          docker push Django_image  

      
      